### ISSUE TITLE
more file format support

### ISSUE THREAD

**Issue by dartagnanli** [Talljack/vscode-auto-space#12]
hi,l like this extend.It's awesome.
when i edit a markdown file ,i use it,but it can not work.more detials below:
``` bash
2023-08-04 17:07:37.948 [error] Error: command 'extension.autoAddSpace' not found
    at y.k (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1510:12265)
    at y.executeCommand (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1510:12194)
2023-08-04 17:07:38.765 [error] TypeError: Cannot read properties of undefined (reading 'document')
	at r.value (/Users/libin/.vscode/extensions/mtxr.sqltools-0.28.0/dist/extension.js:1:79175)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.x (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1972)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2188)
	at b.$acceptEditorPropertiesChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:16937)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7983)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:7749)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:6830)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:5906)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:4736)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at r.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:30355)
	at f.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1902)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2119)
	at y.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:79:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28635)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```
can this extend support more format?or allow to config it?
thanks.

**Comment by Talljack** [comment]
yep, I will check it and try to resolve it, thank your feedback

**Comment by Talljack** [comment]
yep， I test markdown and it can work.
<img width="943" alt="image" src="https://github.com/Talljack/vscode-auto-space/assets/34439652/c7bbc4cb-91b8-4ea0-9cec-85623d3bd6d4">
If you have a problem, can you give me more info about your error, thanks.

**Comment by dartagnanli** [comment]
```json
{
    "autoAddSpace.enable":false
}
```
Above is my conf,by default,"autoAddSpace.comment": "all" is set.,so i don't need to set it.In this case,When i edit a markdown file, i [command + shift + p],and choose `Auto Add Space`,press down enter,an below err occur!
![WX20230820-235548@2x](https://github.com/Talljack/vscode-auto-space/assets/16234056/05f12e05-9d64-465c-bfb1-9241d28f15b3)

**Comment by Talljack** [comment]
Oh, you close autoAddSpace plugin feature, because you set ` "autoAddSpace.enable":false`.
If you want to use this plugin and hope it correct work, you must be set `true` rather than `false`.
Thanks.

**Comment by dartagnanli** [comment]
okk,i got it,thanks for reply me!
